version: '2.4'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/grafana-stuff/afl-dashboard.json:/opt/afl-dashboard.json
      - ${PWD}/grafana-stuff/grafana-provisioning-datasources-influxdb.yaml:/etc/grafana/provisioning/datasources/influxdb.yaml
      - ${PWD}/grafana-stuff/grafana-provisioning-dashboards-afl.yaml:/etc/grafana/provisioning/dashboards/afl.yaml
  influx:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - "INFLUXDB_DB=fuzzing"
  fuzz-bgpd:
    image: qlyoung/fuzzbox-frr
    build:
      context: .
    command: ["bgpd", "2"]
  fuzz-zebra:
    image: qlyoung/fuzzbox-frr
    build:
      context: .
    command: ["zebra", "2"]
  fuzz-pimd:
    image: qlyoung/fuzzbox-frr
    build:
      context: .
    command: ["pimd", "2"]
  fuzz-ospfd:
    image: qlyoung/fuzzbox-frr
    build:
      context: .
    command: ["ospfd", "2"]
