version: '3.3'

configs:
  afl-dashboard:
    file: ./grafana-stuff/afl-dashboard.json
  datasource-influx:
    file: ./grafana-stuff/grafana-provisioning-datasources-influxdb.yaml
  dashboards:
    file: ./grafana-stuff/grafana-provisioning-dashboards-afl.yaml
  my_other_config:
    external: true

services:
  grafana:
    image: grafana/grafana:latest
    #entrypoint: ["sh", "-c", "sleep 2073600"]
    ports:
      - "3000:3000"
    configs:
      - source: afl-dashboard
        target: /opt/afl-dashboard.json
      - source: datasource-influx
        target: /etc/grafana/provisioning/datasources/influxdb.yaml
      - source: dashboards
        target: /etc/grafana/provisioning/dashboards/afl.yaml
  influx:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - "INFLUXDB_DB=fuzzing"
  fuzz-bgpd:
    image: qlyoung/fuzzbox-frr
    build:
      context: .
    command: ["bgpd", "2"]
  fuzz-zebra:
    image: qlyoung/fuzzbox-frr
    build:
      context: .
    command: ["zebra", "2"]
  fuzz-pimd:
    image: qlyoung/fuzzbox-frr
    build:
      context: .
    command: ["pimd", "2"]
  fuzz-ospfd:
    image: qlyoung/fuzzbox-frr
    build:
      context: .
    command: ["ospfd", "2"]
