version: '3.7'

services:
        grafana:
                image: grafana/grafana:latest
                ports:
                        - "3000:3000"

        influx:
                image: influxdb:latest
                ports:
                        - "8086:8086"
        fuzz-bgpd:
                build: .
                args:
                        target: "bgpd"
                        cores: 2
        fuzz-zebra:
                build: .
                args:
                        target: "zebra"
                        cores: 2
        fuzz-pimd:
                build: .
                args:
                        target: "pimd"
                        cores: 2
        fuzz-ospfd:
                build: .
                args:
                        target: "ospfd"
                        cores: 2
